/**
 * @generated by scripts/set-rn-version.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @flow strict
 */

// [TODO(macOS GH#944)
// Note: Be careful not to override these version numbers
// when we merge upstream stable branches into main
// TODO(macOS GH#944)]
exports.version = {
  major: 0,
  minor: 68,
  patch: 31,
  prerelease: null,
};
